### ISSUE TITLE
Multiple UI issues with latest version

### ISSUE THREAD

**Issue by accforgithubtest** [OliveTin/OliveTin#172]
Version=2023.10.09
Environment - Docker Compose set up

Everything was working fine on version 2023.03.25.

Are there any massive / breaking changes that need me to make any changes to the config.yaml file for upgrading from 2023.03.25 to 2023.10.09 ? 

Issues List (!):

On Firefox:
1.  Sidebar has white text on white background in dark mode
![image](https://github.com/OliveTin/OliveTin/assets/128544172/4730b189-bbb3-4487-81ab-700260be956d)
(on hover)
![image](https://github.com/OliveTin/OliveTin/assets/128544172/6cdb68e1-1e32-4865-bc10-918133e7d087)

2. Not displaying anything in case of dropdowns
![image](https://github.com/OliveTin/OliveTin/assets/128544172/f038e3b0-0f07-4aa8-a14c-7e8e91ea2d8a)

On Chrome:
1. Sidebar has white text on white background in dark mode - Same screenshots as firefox.
2. Not displaying the dropdowns properly
![image](https://github.com/OliveTin/OliveTin/assets/128544172/8afddf85-13c3-48d6-aa68-2e32742b432b)

**Comment by jamesread** [comment]
Hey @accforgithubtest , So sorry that I didn't think to check dark mode before pushing out the latest release - indeed it looks like many things are broken! I've just pushed a couple of fixes just now in commit d7ab58, and if that build succeeds I'll push out a patch release later today. Watch this space!

**Comment by jamesread** [comment]
Hey @accforgithubtest , could you please check the 2023.10.12 release to see if this looks better?

**Comment by accforgithubtest** [comment]
@jamesread thank you so much such a quick fix / response. 
I have tried the latest version and dark mode looks good now ! Thanks again.

I do notice some inconsistent behavior when switching to the logs view - Looks like it is not displaying the logs for the execOnCron jobs. Not sure if this is just some issue on my side.

**Comment by edersong** [comment]
For me, those issues persist
Also, the mobile version popup is not showing the buttons for actions.

**Comment by edersong** [comment]
Hello, @jamesread 
First of all, congrats for the handy tool development.
Yes, already tried  Ctrl+F5, clear cookies, etc. but it still ocurring. Also, after the upgrade today.
Follow the screenshots:
![20231024-091834](https://github.com/OliveTin/OliveTin/assets/64137913/f705764e-e5b0-471c-9813-d1bfe8dee3d5)
![2023-10-24 105755](https://github.com/OliveTin/OliveTin/assets/64137913/eb0d9547-dfcd-44f8-82b6-5d60b3c79e56)
![2023-10-24 105824](https://github.com/OliveTin/OliveTin/assets/64137913/431cd131-ca68-466f-90fa-666d3f00603a)
![2023-10-24 105902](https://github.com/OliveTin/OliveTin/assets/64137913/84e344c6-a6a2-4c5a-acfe-489486c51d9a)

**Comment by jamesread** [comment]
Okay, I've gotten myself really confused. Commit d74ab58 contains the fix for this, but I never actually did manage to merge that fix into the 2023.10.12 release it seems. 

I've just created a new PR for this (#180), which I'll queue up for the next release.

What has really confused me, is @accforgithubtest said this was fixed in 2012.10.12 in comment https://github.com/OliveTin/OliveTin/issues/172#issuecomment-1763494553 ... not sure why...

**Comment by edersong** [comment]
Ok, thank you!

**Comment by accforgithubtest** [comment]
Well I am not that bright .. lols.. 

@jamesread - I think I figured out why now - I was trying out a plugin called "Dark Reader" that helps to "auto-create / provide" a dark mode for websites that dont have a dark mode. 

Looks like what has happened is that your earlier fixes actually did fix the dropdowns and text boxes sizes, hence I was able to see them / work with it with Dark Reader doing its thing to switch up the colors.
But actually there is left over issues about the colors in dark mode as mentioned by @edersong !

Will give it another try after your updated release and will remember to disable the dark reader plugin before I try it this time

**Comment by jamesread** [comment]
Okay! Phew, that explains it nicely - thank you!

This fixes have been merged into the main branch now, so the next release should be all you need. 

There's one more feature I want to land before I push that relet out - either later tonight or early tomorrow - check back soon for updates :-)

**Comment by accforgithubtest** [comment]
This is now fixed (I checked with Dark Reader disabled this time 👍 )

**Comment by jamesread** [comment]
Great! @edersong , how about for you? Check you're using at least the 2023.10.25 version.

**Comment by edersong** [comment]
I'm still facing the issue on mobile.
I'm not on my laptop to test it yet.
![1000049995](https://github.com/OliveTin/OliveTin/assets/64137913/37e7be0e-57d0-425e-a02c-f5ccc5675086)

**Comment by jamesread** [comment]
On mobile the most likely cause is that your browser is caching the old stylesheet still - most mobile browsers don't provide a force refresh. Clearing your cache for the site should work. 

Let's see how you get on with your laptop.

**Comment by edersong** [comment]
Working fine now, thanks!!
![image](https://github.com/OliveTin/OliveTin/assets/64137913/593eab7b-1097-4914-9711-d2861c64962b)

**Comment by jamesread** [comment]
Brilliant, so sorry for the bother and confusion on this one. Looks like we've got a fox for everyone now. Let me know if any other issues pop up!
