### ISSUE TITLE
Unselected (blank) Dropdown arguments may cause unexpected behavior

### ISSUE THREAD

**Issue by aholeinthehead** [OliveTin/OliveTin#532]
**Describe the bug**
When an action is defined with a dropdown/choices argument, the resulting form allows the user to submit their response without choosing a response.  This can result in security and stability issues.

**To Reproduce**

- Assume an entity like this:
```yaml
# yaml list of retired sites.  
# Included as 'retired_sites' in our OliveTin entities
- site_directory: customer1
  site_id: customer1-20230103a
- site_directory: customer33
  site_id: customer33-20241121a
- site_directory: customer44
  site_id: customer44-20191225a

```

- Define an action like this:

```yaml
  - title: Remove site directory
    shell: 'rm -rf "/customer_sites/{{ SiteDirectory }}"'
    popupOnStart: execution-dialog
    arguments:
      - name: SiteDirectory
        entity: retired_sites
        title: Retired Site directory
        choices:
          - title: '{{retired_sites.site_directory}} ({{retired_sites.site_id}})'
            value: '{{retired_sites.site_directory}}'

```

When executed, if the user makes no selection, the command is run as:

`rm -rf "/customer_sites/"`

This deletes all customer sites.  Not just the selected, retired one.

**Expected behavior**
The form should require a selection, refusing to continue if none is made.

**Additional context**
A workaround is possible by using an external script to perform sanity checking.  However, this greatly complicates the implementation.  It's _so close_ to being safe for use.  It just needs one little safeguard.

**Suggested fix**
A boolean option for the `choices` map,  `required: (true|false)` would preserve the current functionality, but allow OliveTin admins to define this action to behave in a more controlled, predictable way.

**Comment by jamesread** [comment]
Heya @aholeinthehead , 

Just a quick reply on mobile, I'm not sure if this option is documented, but can you try `rejectNull: true` on the argument?

**Comment by aholeinthehead** [comment]
Holy cow!  This has to be some kind of a record response time.  Thank you, @jamesread !

I added `rejectNull: true` to my action, and it indeed failed with:

```
null values are not allowed
```

Perfect!

**Comment by aholeinthehead** [comment]
I am not sure about the etiquette of closing the bug in this situation.  Ideally, a documentation update is needed to resolve this issue properly.  However, I am very grateful for your quick help, which has gotten me back on track with my project much quicker than I expected.  

I'll leave it open to be closed at your discretion however you want to handle it.

**Comment by jamesread** [comment]
Heya @aholeinthehead , you're welcome, and I'm glad it worked for you 😊 

I was just throwing together a quick doc page for it, and just pushed it live even with a few typos, just so there's something there: https://docs.olivetin.app/args/common.html

I always feel issues should only get closed when a solution is provides that that OP agrees would have prevented the issue. Do you think that doc page would have helped? 

Maybe it's better to include the common argument options on every page for each type?

**Comment by aholeinthehead** [comment]
I believe that page would have led me to the solution.  However, I probably would have been clicking around a bit aimlessly to find it there.  Including rejectNull on each input type - even if just in one of the examples - would definitely make it more obvious to the implementer that this parameter exists.  As a bonus, having it repeated throughout the documentation would likely lead to safer implementations generally, since it would cue the reader that they should consider the circumstance of null inputs.

**Comment by jamesread** [comment]
Yeah, as I wrote that last reply I thought that would be the better option too. I'll adjust the docs tomorrow to do that, and include the other undocumented options too.

May I ask you for your time to re-review when that change is ready?

**Comment by aholeinthehead** [comment]
I'd be happy to.  I'm at UTC-5, so it might take a little time to overlap our efforts, but I'll jump on it as soon as I can.

**Comment by Maokaman1** [comment]
Hi,

The `rejectNull` option doesn't perform any validation when arguments are omitted in the `shell` key and used as environment variables within scripts.
This may indicate that other important validation checks are also being skipped when arguments aren't explicitly passed as shell command arguments.
Additionally, when multiple arguments are checked with `rejectNull`, the system doesn't indicate which specific argument is null.
Client-side form validation would improve the user experience for this issue, similar to how it currently works for other Input types.

**Comment by jamesread** [comment]
@Maokaman1 , many thanks for this extra comment. Let me reply with some pointers to the code - I'm not asking you to understand the code necessarily, but they serve as a good way to remind me what I've looked at when I come to potentially patching this!

> The rejectNull option doesn't perform any validation when arguments are omitted in the shell key and used as environment variables within scripts.

This surprised me, but you're absolutely right. 

Only arguments that are explicitly used in the shell command are validated. You can see this behavior in this part of the code; https://github.com/OliveTin/OliveTin/blob/7788f58aac7364bead205062103c622bce13195f/internal/executor/arguments.go#L31 I'm not sure why I wrote it like that, the obvious fix is to "typecheck" (validate) all arguments, irrespective of if they are used. There might be a reason why I didn't do that, as it seems like the obvious approach. I'll need to read the code in more detail to check that. 

I hadn't considered that those argument values are still available via environment variables (which was added much later after argument validation), and those values would not be validated. 

> Additionally, when multiple arguments are checked with rejectNull, the system doesn't indicate which specific argument is null.

Agreed, the null validation check also does not include the argument name - as defined here https://github.com/OliveTin/OliveTin/blob/7788f58aac7364bead205062103c622bce13195f/internal/executor/arguments.go#L104 - which indeed could be a pain. Infact I'm surprised that I'm not capturing the argument name at all with the error - that would be useful for the UI, and better error messages. Reference: https://github.com/OliveTin/OliveTin/blob/7788f58aac7364bead205062103c622bce13195f/internal/executor/arguments.go#L62 

> Client-side form validation would improve the user experience for this issue, similar to how it currently works for other Input types.

For security reasons, all the arguments need to be validated on the server side, but for usability, the checks also happen on the client-side in 2 ways - for arguments like "regex", browsers support that regex parsing as well now-a-days and can display richer error messages. Also, the web client sends an fetch request to the server to validate each argument as you type - (code here: https://github.com/OliveTin/OliveTin/blob/7788f58aac7364bead205062103c622bce13195f/internal/grpcapi/grpcApi.go#L361 ) - which allows errors to be displayed quicker. Teh arguments are validated again when the action is actually executed.

So, thanks for these extra comments - these little edge cases are easy to miss, but I'm more than happy to patch. Give me a bit of time to write up some test cases for these though, and I'll try and release a patch as soon as my free time allows :-)

**Comment by jamesread** [comment]
Heya @aholeinthehead , @Maokaman1 , thanks for your patience waiting for this - it's been a busy few weeks!

I've just released **2025.4.21** that should address these remaining issues. It would be great if you have time to validate that they're fixed on your side. Please be careful when you test with the latest release, do it in a safe test environment, don't risk doing something like `rm -rf /customers/{{ test }}/` if `test` is blank (although that should be fixed now - see below

# Argument values not specified explicitly in the `shell:` are now validated

This release now validates all argument values before trying to build the final command line, and argument values that are not explicitly in the `shell:` command are still validated. This is necessary incase those argument values are used via environment variables for example.

I added a test for this as well, here; 

https://github.com/OliveTin/OliveTin/blob/eb2721c023de82cdf1b8e01bebc730aad0a5b28e/service/internal/executor/executor_test.go#L203

Could you let me know if this is good for you, and if you're OK to close the issue?

**Comment by Maokaman1** [comment]
While client-side validation for 'rejectNull' is still missing, the backend now correctly handles cases where arguments are omitted in the 'shell' key (e.g., when passed via environment variables), ensuring validation is no longer skipped.
Thanks, @jamesread!

**Comment by jamesread** [comment]
Thanks for checking @Maokaman1 , the client side check is only a "nice to have" helper in the UI, so I am closing this as resolved :-) Thanks for your help in testing the fix!
