### ISSUE TITLE
Navigation is shown even if "showNavigation: false"

### ISSUE THREAD

**Issue by mueller-ma** [OliveTin/OliveTin#685]
**Describe the bug**
After updating to 3k the navigation bar is shown, when `showNavigation: false` is configured. The hamburger icon has no function, i.e. it doesn't open the side menu, but it's sill shown.

**To Reproduce**
1. Set `showNavigation: false`
2. Open website

**Expected behavior**
Anything shown on the screenshot should be hidden.

**Screenshots**
<img width="1918" height="111" alt="Image" src="https://github.com/user-attachments/assets/77549dcc-9bf1-4858-bbe3-6378748b5114" />

**Additional context**

The login button could be hidden anyway, since it only shows following page:

<img width="351" height="156" alt="Image" src="https://github.com/user-attachments/assets/6a532726-5d9d-4825-9a59-de3718dc8e3e" />

**Comment by jamesread** [comment]
Hey @mueller-ma , thanks for taking time to report this bug, and your patience for a few days until I had time to patch it.

I have just released 3000.3.1 that should contain the fix for this bug. Please could you test and let me know? Thanks!

https://github.com/OliveTin/OliveTin/releases/tag/3000.3.1

**Comment by mueller-ma** [comment]
The navigation is hidden now, the login button still shown. Do you want a new issue for that?

**Comment by jamesread** [comment]
@mueller-ma Raised a new one myself - #696 . thanks! 

Ok to close this issue?

**Comment by mueller-ma** [comment]
Thanks for fixing this :)
