### ISSUE TITLE
Inconsistent fieldset order when using entities

### ISSUE THREAD

**Issue by mzaja** [OliveTin/OliveTin#762]
**Describe the bug**
Entities are rendered in the inconsistent order. The order appears random and changes on refresh. Sometimes, duplicate entries are rendered, despite there being no duplicate entities.

**To Reproduce**
Use the following configuration and start **OliveTin 3000.4.0**:
`config.yaml`:
```yaml
actions:
  - title: Check Status {{ .CurrentEntity.Id }}
    icon: ping
    popupOnStart: execution-dialog
    entity: timer
    shell: | 
      systemctl status --no-pager {{ .CurrentEntity.Id }} 
      systemctl status --no-pager --full {{ .CurrentEntity.Unit }} || true

entities:
  - name: timer
    file: ./timer_bug.json

dashboards:
  - title: systemd monitor  # Name of the panel (selectable from the sidebar)
    contents:
      - title: '{{ .CurrentEntity.Unit }}'
        type: fieldset
        entity: timer
        contents:
          - title: |
              Result: <strong>{{ .CurrentEntity.Result }}</strong> <br>
              Last activation: {{ .CurrentEntity.LastTriggerUSec }}<br>
              Next activation: {{ .CurrentEntity.NextElapseUSecRealtime }}
            type: display
          - title: Check Status {{ .CurrentEntity.Id }}

```

Entities file (`timer_bug.json`):
```json
{
  "Unit": "scraper.service",
  "NextElapseUSecRealtime": "Sun 2025-11-23 15:05:00 UTC",
  "LastTriggerUSec": "Sat 2025-11-22 15:05:04 UTC",
  "Result": "success",
  "Id": "scraper.timer"
}
{
  "Unit": "downloader.service",
  "NextElapseUSecRealtime": "Sun 2025-11-23 08:00:00 UTC",
  "LastTriggerUSec": "Sat 2025-11-22 08:00:04 UTC",
  "Result": "success",
  "Id": "downloader.timer"
}
{
  "Unit": "another-scraper.service",
  "NextElapseUSecRealtime": "Mon 2025-11-24 00:00:05 UTC",
  "LastTriggerUSec": "Sun 2025-11-23 00:00:21 UTC",
  "Result": "success",
  "Id": "another-scraper.timer"
}
```

**Expected behavior**
- The labels/buttons in each row are rendered in the same order that the entities appear in the entities file.
- The order is consistent and does not change on refresh.
- Each entity's row is rendered only once.

In the example above, the expected order of rendered entities is:
1. scraper.service
2. downloader.service
3. another-scraper.service

In each row, the name on the row label and the name on the `Check Status` button should match (service name paired with the corresponding timer name).

**Screenshots**
The layout of the generated panel changes on each refresh. Here are some examples of erroneous rendering:
Example 1: 
- The order of row labels is inverse of the order in which the entities are defined in the entity file.
- `scraper.timer` appears on all three buttons, while `another-scraper.timer` and `downloader.timer` do not appear at all.
<img width="1183" height="647" alt="Image" src="https://github.com/user-attachments/assets/d43abbf0-859f-450b-8c23-03d8b05adc83" />

Example 2 (on refresh):
- The order of row labels is still inverse of the order in which the entities are defined. This appears to be consistent over refreshes.
- The names associated with `Check Status` buttons have now changed. They are still wrong, as the button names mismatch for the first two rows.
- `scraper.timer` appears twice on the buttons, while `another-scraper.timer` does not appear at all.
<img width="1176" height="645" alt="Image" src="https://github.com/user-attachments/assets/cf2d2084-eb2a-4b00-930a-bf9f64f66315" />

**Additional context**

**Comment by jamesread** [comment]
HEya @mzaja , this looks like a duplicate of #703, could you check?

**Comment by mzaja** [comment]
Hi @jamesread. Yes, it certainly looks like the same issue.

**Comment by mzaja** [comment]
I would hazard a guess this is caused by storing the values of entities in a hash map, which does not have a defined order: https://stackoverflow.com/questions/18342784/how-to-iterate-through-a-map-in-golang-in-order

Of course, I might be completely wrong. I did not study the code to see what exactly goes in the backend, but I have seen plenty of bugs similar to this when using sets in Python (or dictionaries on old versions of the interpreter).

**Comment by mzaja** [comment]
I have reproduced this issue now even without using entities. I have generated a bunch of actions with indexes starting from 0, and I have also referenced them inside the dashboard in the same order. One would therefore expect the buttons to have indexes 0, 1, 2, 3... However, that is not the case, and the order seems quasi-random. However, unlike with entities, the order does persist over page refreshes and even stopping and restarting OliveTin.

<img width="208" height="721" alt="Image" src="https://github.com/user-attachments/assets/d4ae1c0f-b760-4f88-baed-7d20350f4bdf" />

**Comment by jamesread** [comment]
Heya @mzaja , thanks for taking the time to report this - I pushed out a big new release - 3000.5.0 last night that should certainly address the first 2 issues; 

- Entity ordering being random
- Fieldset titles (legends) being aligned to the right.

The 3rd issue with the button ordering is more complex - how that button ordering works. I'll have to look at that separately.

**Comment by jamesread** [comment]
Hey @mzaja , I took another run at this. Could you take a look at version 3000.6.0 and let me know how you get on?

**Comment by mzaja** [comment]
Hi @jamesread. Sorry for taking so long to reply. I have tested this on 3000.7.0, and unfortunately, the issue is still present. As you can see in the attached screenshot, the numerical index of buttons is still (quasi-)random, while the order in which the button titles are provided in the config file is monotonic, from 0 to 7. The order shown on the attached image persists through restarts.

<img width="229" height="1204" alt="Image" src="https://github.com/user-attachments/assets/84adf238-2fcd-4eb8-a4c9-dd0e3f802f82" />

**Comment by bl4ckswordsman** [comment]
The issue is present for me as well, in 3000.9.2

**Comment by mzaja** [comment]
Still present in 3000.9.4. The order of buttons, although not as expected, seems to be consistent across versions: 3 5 1 2 0 4 6 7.

**Comment by jamesread** [comment]
Reopening

**Comment by jamesread** [comment]
Hey @mzaja , I took some time to write proper spec for this and tests, and made some improvements in 3000.11.2. Would you mind taking a look?

The spec is https://github.com/OliveTin/OliveTin/blob/main/specs/dashboard-component-ordering.md

**Comment by jamesread** [comment]
I've heard from several people that this is working as they'd expect now. Please do reopen this if needed.
